### ISSUE TITLE
duplicate argument

### ISSUE THREAD

**Issue by INGCRENGIFO** [pulumi/pulumi-cloudflare#229]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

bug with pulumi_cloudflare-4.4.0, with the version 4.3 all ok

### Steps to reproduce

error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/usr/bin/pulumi-language-python-exec", line 92, in <module>
        loop.run_until_complete(coro)
      File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
        return future.result()
      File "/usr/local/lib/python3.7/site-packages/pulumi/runtime/stack.py", line [126](https://github.com/Liftitapp/lms-mf-logistics/runs/5381931495?check_suite_focus=true#step:4:126), in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/usr/local/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 49, in run_pulumi_func
        func()
      File "/usr/local/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 126, in <lambda>
        await run_pulumi_func(lambda: Stack(func))
      File "/usr/local/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 149, in __init__
        func()
      File "/usr/bin/pulumi-language-python-exec", line 91, in <lambda>
        coro = pulumi.runtime.run_in_stack(lambda: runpy.run_path(args.PROGRAM, run_name='__main__'))
      File "/usr/local/lib/python3.7/runpy.py", line 280, in run_path
        run_name, mod_spec, pkg_name).copy()
      File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "./__main__.py", line 5, in <module>
        import pulumi_cloudflare as cloudflare
      File "/usr/local/lib/python3.7/site-packages/pulumi_cloudflare/__init__.py", line 29, in <module>
        from .device_posture_integration import *
      File "/usr/local/lib/python3.7/site-packages/pulumi_cloudflare/device_posture_integration.py", line 371
        @staticmethod
        ^
    SyntaxError: duplicate argument 'id' in function definition
    error: an unhandled error occurred: Program exited with non-zero exit code: 1

My requirenments.txt is

pulumi>=3.25.0
pulumi-gcp==6.14.0
pulumi-random>=4.3.1
pulumi_cloudflare>=4.3.0

push.yml (github action)
pulumi-up:
    name: Pulumi - Update
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/devs'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: docker://pulumi/actions
        with:
          args: up --yes
        env:
          GOOGLE_CREDENTIALS: xxxx
          PULUMI_ACCESS_TOKEN: xxxx
          CLOUDFLARE_ACCOUNT_ID: xxxx
          CLOUDFLARE_API_TOKEN: xxxx
          PULUMI_CI: up
          PULUMI_ROOT: xxxx

**Comment by guineveresaenger** [comment]
Thank you for reporting this - there does indeed seem a duplicate field in that package.

The issue does [not seem to be upstream](https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/cloudflare%2Fresource_cloudflare_device_posture_integration.go) but rather be an error in our package code gen.

**Comment by stack72** [comment]
Just circling back here - https://github.com/cloudflare/terraform-provider-cloudflare/pull/1504
