### ISSUE TITLE
Panics when importing and refreshing  cloudflare:index:Ruleset with RulesetRuleActionParametersEdgeTtlStatusCodeTtl 

### ISSUE THREAD

**Issue by tomski747** [pulumi/pulumi-cloudflare#436]
### What happened?

Importing and refreshing resources of kind `cloudflare:index:Ruleset`, which include `RulesetRuleActionParametersEdgeTtlStatusCodeTtl`, leads to crashes starting from version 5.1.1. 

These breaking schema changes were identified in the PR for version 5.1.1: [Link to PR](https://github.com/pulumi/pulumi-cloudflare/pull/406#issuecomment-1548338582). 

However, it seems that they have not been handled correctly.

### Expected Behavior

Should work as it worked in 5.0.0

### Steps to reproduce

```
➜ cat index.ts 

import * as cloudflare from "@pulumi/cloudflare";

new cloudflare.Ruleset("my-ruleset", {
    zoneId: "XXX",
    phase: "http_request_cache_settings",
    kind: "zone",
    name: "Debug Rulesets",
    rules: [
        {
            action: "set_cache_settings",
            expression: '(http.host eq "google.com")',
            description: "Debug Rulesets",
            enabled: true,
            actionParameters: {
                cache: true,
                browserTtl: {
                    mode: "respect_origin",
                },
                edgeTtl: {
                    mode: "override_origin",
                    default: 60 * 60 * 24 * 365, // 1 year (or purge)
                    statusCodeTtls: [
                        {
                            statusCodeRanges: [
                                {
                                    from: 299,
                                    to: 999,
                                },
                            ],
                            value: -1,
                        },
                    ],
                },
            },
        },
    ],
});

➜  pulumi refresh  -y --debug --verbose=0
Previewing refresh (dev)

View Live: https://app.pulumi.com/tomski747/tmp-cf/dev/previews/f3638180-a180-465a-a935-6a759df53ebb

     Type                         Name        Plan        Info
     pulumi:pulumi:Stack          tmp-cf-dev              1 error; 49 messages
 ~   └─ cloudflare:index:Ruleset  lambdaName  refresh     1 error


Diagnostics:
  pulumi:pulumi:Stack (tmp-cf-dev):
       provider/config.go:38: provider: cloudflare Client configured for user: : provider=cloudflare@v5.1.1
    error: preview failed

    panic: Missing key: status_code_ranges
    goroutine 83 [running]:
    github.com/pulumi/pulumi-terraform-bridge/pf/internal/schemashim.(*objectPseudoResource).Get(0x14000d05530?, {0x140003886d8, 0x12})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/pf@v0.9.0/internal/schemashim/object_pseudoresource.go:112 +0x84
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.getSchema(...)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.47.2/pkg/tfbridge/schema.go:259
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.getInfoFromPulumiName({0x14000d05530, 0x10}, {0x101640e38, 0x14000237900}, 0x14000237900?, 0x0)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.47.2/pkg/tfbridge/schema.go:1178 +0x188
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.extractInputs({{0x1015ac6a0?, 0x14000408990?}}, {{0x1015ac6a0?, 0x140005f1350?}}, {0x10164be60, 0x14000752180?}, 0x0?, 0x0)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.47.2/pkg/tfbridge/schema.go:1304 +0x450
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.extractInputs({{0x1013a2d80?, 0x14000e0a168?}}, {{0x1013a2d80?, 0x14000d06c90?}}, {0x10164bc20?, 0x1400013e280?}, 0x14000aba398?, 0x0)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.47.2/pkg/tfbridge/schema.go:1268 +0x864
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.extractInputs({{0x1015ac6a0?, 0x14000408780?}}, {{0x1015ac6a0?, 0x140005f1260?}}, {0x10164bc20, 0x14000369b80?}, 0x0?, 0x0)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.47.2/pkg/tfbridge/schema.go:1305 +0x4ac
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.extractInputs({{0x1015ac6a0?, 0x14000408210?}}, {{0x1015ac6a0?, 0x14000895d70?}}, {0x10164bc20, 0x140003686c0?}, 0x140005d76c0?, 0x0)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.47.2/pkg/tfbridge/schema.go:1305 +0x4ac
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.extractInputs({{0x1015ac6a0?, 0x14000408180?}}, {{0x1015ac6a0?, 0x14000895440?}}, {0x10164be60, 0x140007520c0?}, 0x140005d7450?, 0x0)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.47.2/pkg/tfbridge/schema.go:1305 +0x4ac
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.extractInputs({{0x1013a2d80?, 0x14000e0a360?}}, {{0x1013a2d80?, 0x14000d06db0?}}, {0x10164bc20?, 0x140003685a0?}, 0x6401abb018?, 0x0)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.47.2/pkg/tfbridge/schema.go:1268 +0x864
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.extractInputs({{0x1015ac6a0?, 0x14000408120?}}, {{0x1015ac6a0?, 0x140008952f0?}}, {0x10164be60, 0x14000752000?}, 0x14000abb298?, 0x0)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.47.2/pkg/tfbridge/schema.go:1305 +0x4ac
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.ExtractInputsFromOutputs(0x1016431d0?, 0x14000a4ab40?, {0x101640e80?, 0x14000571060}, 0x140005d4120, 0x1)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.47.2/pkg/tfbridge/schema.go:1453 +0x108
    github.com/pulumi/pulumi-terraform-bridge/pf/tfbridge.(*provider).ReadWithContext(0x14000279600, {0x10163d208?, 0x140003c4720?}, {0x14000d72000, 0x44}, {0x1400036ca40, 0x20}, 0x1013c2180?, 0x140003c4780)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/pf@v0.9.0/tfbridge/provider_read.go:69 +0x204
    github.com/pulumi/pulumi-terraform-bridge/pf/internal/plugin.(*providerServer).Read(0x140006a5800, {0x10163d208, 0x140003c4720}, 0x14000d00ea0)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/pf@v0.9.0/internal/plugin/provider_server.go:370 +0x198
    github.com/pulumi/pulumi-terraform-bridge/x/muxer.(*muxer).Read.func1({0x10164ac10?, 0x140006a5800?})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.3/muxer.go:348 +0x3c
    github.com/pulumi/pulumi-terraform-bridge/x/muxer.resourceMethod[...](0x14000890370?, 0x14000d7d778, 0x14000d7d758?)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.3/muxer.go:301 +0xc4
    github.com/pulumi/pulumi-terraform-bridge/x/muxer.(*muxer).Read(0x14000d7d7b8?, {0x10163d208?, 0x140003c4720?}, 0x1013cba00?)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.3/muxer.go:347 +0x5c
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Read_Handler.func1({0x10163d208, 0x140003c4720}, {0x10156c8c0?, 0x14000d00ea0})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.64.0/proto/go/provider_grpc.pb.go:591 +0x74
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x10163d208, 0x140003772c0}, {0x10156c8c0, 0x14000d00ea0}, 0x140007e7b00, 0x14000d074d0)
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x2f4
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Read_Handler({0x1015ee4c0?, 0x14000890370}, {0x10163d208, 0x140003772c0}, 0x14000190070, 0x14000450e60)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.64.0/proto/go/provider_grpc.pb.go:593 +0x12c
    google.golang.org/grpc.(*Server).processUnaryRPC(0x140003130e0, {0x101645020, 0x14000c6da00}, 0x140007d8000, 0x140006a5890, 0x102087f38, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.54.0/server.go:1345 +0xc28
    google.golang.org/grpc.(*Server).handleStream(0x140003130e0, {0x101645020, 0x14000c6da00}, 0x140007d8000, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.54.0/server.go:1722 +0x80c
    google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.54.0/server.go:966 +0x84
    created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.54.0/server.go:964 +0x278

  cloudflare:index:Ruleset (lambdaName):
    error: Preview failed: error reading from server: EOF

```

### Output of `pulumi about`

```
➜  pulumi about      
CLI          
Version      3.53.1
Go Version   go1.19.5
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       darwin
Version  13.0
Arch     arm64

This project is written in nodejs: executable='/Users/tom/.nvm/versions/node/v18.16.0/bin/node' version='v18.16.0'

Current Stack: tomski747/tmp-cf/dev

TYPE                              URN
pulumi:pulumi:Stack               urn:pulumi:dev::tmp-cf::pulumi:pulumi:Stack::tmp-cf-dev
pulumi:providers:cloudflare       urn:pulumi:dev::tmp-cf::pulumi:providers:cloudflare::default_5_1_1
cloudflare:index/ruleset:Ruleset  urn:pulumi:dev::tmp-cf::cloudflare:index/ruleset:Ruleset::lambdaName


Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/tomski747
User           tomski747
Organizations  tomski747, descope

Pulumi locates its logs in /var/folders/nk/svhsmg8j53z64qbq_hnltm2w0000gn/T/ by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
Thank you for reporting this! My team is having a look.
