### ISSUE TITLE
Reading cloudflare:index:Ruleset Causes Panic

### ISSUE THREAD

**Issue by dmizelle** [pulumi/pulumi-cloudflare#460]
### What happened?

On the latest version of the provider (v5.7.0 at time of writing) we're attempting to import a `cloudflare:index:Ruleset` resource into our stack and running into the following `panic`:

```
Diagnostics:
  cloudflare:index:Ruleset (CDN Optimization Rules):
    error: Preview failed: error reading from server: EOF
 
  pulumi:pulumi:Stack (infrastructure-main):
    panic: DefaultValue() should not be called during schema generation
    goroutine 106 [running]:
    github.com/pulumi/pulumi-terraform-bridge/pf/internal/schemashim.(*blockSchema).DefaultValue(0xc000730870)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/pf@v0.9.2/internal/schemashim/block_schema.go:123 +0x27
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.getDefaultValue(...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.51.0/pkg/tfbridge/schema.go:1350
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.isDefaultOrZeroValue({0x18c2780, 0xc00116c840}, 0x18c2780?, {{0x13819e0?, 0xc0001a5278?}})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.51.0/pkg/tfbridge/schema.go:1361 +0x44
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.extractSchemaInputs({{0x158f780?, 0xc001211920?}}, {0x18c29c0, 0xc0011115c0}, 0xc000d712c0?, 0x0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.51.0/pkg/tfbridge/schema.go:1438 +0x3e6
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.ExtractInputsFromOutputs(0x18b9810?, 0xc0005fa820?, {0x18b7448?, 0xc001179ed0}, 0xc000730870, 0x0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.51.0/pkg/tfbridge/schema.go:1468 +0x15f
    github.com/pulumi/pulumi-terraform-bridge/pf/tfbridge.(*provider).ReadWithContext(0xc00025f600, {0x18b36c8?, 0xc000614b70?}, {0xc0011c6a00, 0x9d}, {0xc000aa89b0, 0x46}, 0x0?, 0xc000614bd0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/pf@v0.9.2/tfbridge/provider_read.go:69 +0x2f9
    github.com/pulumi/pulumi-terraform-bridge/pf/internal/plugin.(*providerServer).Read(0xc000436870, {0x18b36c8, 0xc000614b70}, 0xc0007bf9e0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/pf@v0.9.2/internal/plugin/provider_server.go:370 +0x188
    github.com/pulumi/pulumi-terraform-bridge/x/muxer.(*muxer).Read.func1({0x18c1770?, 0xc000436870?})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.4/muxer.go:350 +0x39
    github.com/pulumi/pulumi-terraform-bridge/x/muxer.resourceMethod[...](0xc0005fad20?, 0x40, 0xc00010f780?)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.4/muxer.go:303 +0xbd
    github.com/pulumi/pulumi-terraform-bridge/x/muxer.(*muxer).Read(0x0?, {0x18b36c8?, 0xc000614b70?}, 0x40?)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.4/muxer.go:349 +0x68
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Read_Handler.func1({0x18b36c8, 0xc000614b70}, {0x154f420?, 0xc0007bf9e0})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.72.2/proto/go/provider_grpc.pb.go:591 +0x7b
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x18b36c8, 0xc0006148a0}, {0x154f420, 0xc0007bf9e0}, 0xc00003ff00, 0xc0005e5ab8)
    	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x3e8
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Read_Handler({0x15d1b60?, 0xc0005fad20}, {0x18b36c8, 0xc0006148a0}, 0xc0006af810, 0xc000434080)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.72.2/proto/go/provider_grpc.pb.go:593 +0x138
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc000630000, {0x18bb640, 0xc000aaa000}, 0xc00030fe60, 0xc000436900, 0x23a1ed8, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.56.0/server.go:1337 +0xdf3
    google.golang.org/grpc.(*Server).handleStream(0xc000630000, {0x18bb640, 0xc000aaa000}, 0xc00030fe60, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.56.0/server.go:1714 +0xa36
    google.golang.org/grpc.(*Server).serveStreams.func1.1()
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.56.0/server.go:959 +0x98
    created by google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.56.0/server.go:957 +0x18c
    error: preview failed
```

We thought that it was originally how we were importing the resource (something like maybe one of the parameters we were passing) but upon trying to create a minimal reproduction of the issue by just reading the `RulesSet` via a getter, we see the same panic.

See the "Steps to Reproduce" section for how we were able to reproduce it.

When we downgraded back to `v5.0.0`, we were able to read the resource successfully. 

The issue may have been introduced in `v5.1.0`, but we are unable to run the provider (there was a bug fixed in #406). `v5.1.1` was the first actual version where we could see the bug when we were attempting to "walk" versions.

### Expected Behavior

We initially expected to be able to import the resource successfully.

In our minimum reproduction, we should be able to `pulumi.export()` the attributes of the resource without a `panic`.

### Steps to reproduce

I created our minimal reproduction via Docker.

Start a container with:

```
$ docker run --rm -it ubuntu:22.04
```

Inside the container, run a few things to bootstrap the environment:

```
apt update && apt install -y curl python3 python3.10-venv
curl -fsSL https://get.pulumi.com/ | sh
export PATH=~/.pulumi/bin:$PATH
pulumi login --local
mkdir /tmp/testing
cd /tmp/testing
python3 -m venv .
source bin/activate
pip install pulumi pulumi-cloudflare
export CLOUDFLARE_API_TOKEN="OUR_TOKEN_HERE"
export PULUMI_CONFIG_PASSPHRASE="foobar"
```

Create a `requirements.txt` with the following:

```
Arpeggio==2.0.2
attrs==23.1.0
dill==0.3.7
grpcio==1.56.0
parver==0.4
protobuf==4.23.4
pulumi==3.76.1
pulumi-cloudflare==5.7.0
PyYAML==6.0.1
semver==2.13.0
six==1.16.0
```

Install the requirements with:
```
pip install -r requirements.txt
```

Using the automation API, create a script like the following. Be sure to replace the values of `ZONE_ID` and `RULESET_ID`.

```python
import json
import sys

import pulumi
import pulumi_cloudflare as cloudflare
from pulumi import automation as auto

ZONE_ID = "09deadbeef"
RULESET_ID="09badcaffe"

def prog():
    ruleset = cloudflare.Ruleset.get(
        "ruleset",
        f"zone/{ZONE_ID}/{RULESET_ID}",
    )

    pulumi.export("ruleset", ruleset)


project_name = "testing"
stack_name = "testing"
stack = auto.create_or_select_stack(
    stack_name=stack_name, project_name=project_name, program=prog
)

stack.workspace.install_plugin("cloudflare", "v5.7.9")
print("plugins installed")

stack.refresh(on_output=print)

stack.preview(on_output=print)
```

The refresh is successful, but when you start doing the preview, the `panic` occurs.

### Output of `pulumi about`

Other notes:

- Arch is `aarch64` as I am on an M1 Mac currently. Our runners where the initial `panic` occurred during CI run `x86_64`.
- The warnings are just because I'm using the automation API, so there's no project or stack file.
- `root` because I'm lazy and in a Docker container.

```CLI
Version      3.76.1
Go Version   go1.20.6
Go Compiler  gc

Host
OS       ubuntu
Version  22.04
Arch     aarch64

Backend
Name           c131e0286c4d
URL            file://~
User           root
Organizations

Pulumi locates its logs in /tmp by default
warning: Failed to read project: no Pulumi.yaml project file found (searching upwards from /tmp/testing). If you have not created a project yet, use `pulumi new` to do so: no project file found
warning: Failed to get information about the current stack: no Pulumi.yaml project file found (searching upwards from /tmp/testing). If you have not created a project yet, use `pulumi new` to do so: no project file found
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
@guineveresaenger Could you please take a look?

**Comment by t0yv0** [comment]
I got context here. It's a plugin framework bug in the bridge. What happened is that 
tfbridge.ExtractInputsFromOutputs
got reused from the sdk/v2 bridge which is no longer safe as it passes schema-only provider shim into sdk/v2 bridge machinery. The schema-only provider is not equipped for runtime use, hence we get `DefaultValue() should not be called during schema generation` while not being in the schema generation context anymore. A possible fix here is to wrap the schema-only provider when passing to tfbridge.ExtractInputsFromOutputs or use a weaker interface in tfbridge.ExtractInputsFromOutputs. In the Plugin Framework case there is no capability currently to detect default values for properties; but proceeding as if no default value is defined is preferable to having a panic.

**Comment by guineveresaenger** [comment]
Hi @dmizelle - this should be fixed on the next release of this provider!
